//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dvhBaiKiemTraGK.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dvhK22CNT1Lesson07DbEntities1 : DbContext
    {
        public dvhK22CNT1Lesson07DbEntities1()
            : base("name=dvhK22CNT1Lesson07DbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dvhKhoa> dvhKhoa { get; set; }
    }
}
